# Generated by Django 5.1.6 on 2025-02-07 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pedido_observacoes_pedido_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='email',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(default=0, max_length=18, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor'),
        ),
    ]
