# Generated by Django 5.1.6 on 2025-02-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_plano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default='Desconhecido', max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default='00000-000', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rua',
            field=models.CharField(default='Desconhecido', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
