# Generated by Django 5.1.6 on 2025-02-17 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pedido_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='data_avaliacao',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='pedido',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
