# Generated by Django 5.1.6 on 2025-02-17 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_data_avaliacao_avaliacao_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinatura',
            name='tipo',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='plano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.plano'),
            preserve_default=False,
        ),
    ]
